@startuml
|Клієнт|
start
:Адміністратор відкриває екран "Список книг";

|Сервер|
:Сервер отримує запит на список книг;
:Сервер запитує дані з бази даних;

if (Дані успішно отримано?) then (Так)
  :Сервер відправляє список книг клієнту;
else (Ні)
  :Сервер повертає повідомлення про помилку;
endif

|Клієнт|
if (Дані отримано?) then (Так)
  :Відображення списку книг на екрані;
  if (Адміністратор вибирає дію?) then (Так)
    switch (Дія)
      case (Перегляд детальної інформації)
        :Клієнт відкриває сторінку книги;
      case (Редагування книги)
        :Клієнт переходить на форму редагування;
      case (Видалення книги)
        :Клієнт надсилає запит на видалення;
        |Сервер|
        :Сервер видаляє книгу і оновлює дані;
        |Клієнт|
        :Оновлення списку на екрані;
    endswitch
  else (Ні)
    :Адміністратор переглядає список книг;
  endif
else (Ні)
  :Виведення повідомлення про помилку;
endif
stop
@enduml
