@startuml
|Клієнт|
start
:Адміністратор відкриває форму "Редагування книги";
:Адміністратор вводить унікальний _id книги;
:Адміністратор змінює дані (назва, автор, рік публікації);
:Клієнт відправляє дані на сервер;

|Сервер|
:Сервер отримує _id та оновлені дані книги;
:Сервер перевіряє існування книги в базі;

if (Книга існує?) then (Так)
  :Сервер оновлює дані книги в базі;

  if (Оновлення успішне?) then (Так)
    :Сервер повертає успішну відповідь;
  else (Ні)
    :Сервер повертає повідомлення про помилку оновлення;
  endif
else (Ні)
  :Сервер повертає повідомлення "Книга не знайдена";
endif

|Клієнт|
if (Відповідь успішна?) then (Так)
  :Клієнт відображає повідомлення "Книга оновлена успішно";
else (Ні)
  :Клієнт відображає повідомлення про помилку або "Книга не знайдена";
endif
stop
@enduml
