@startuml
|Клієнт|
start
:Адміністратор обирає опцію "Видалити книгу";
:Адміністратор вводить унікальний _id книги;
:Клієнт відправляє запит на видалення книги на сервер;

|Сервер|
:Сервер отримує _id книги;
:Сервер перевіряє існування книги в базі;

if (Книга існує?) then (Так)
  :Сервер видаляє книгу з бази;

  if (Видалення успішне?) then (Так)
    :Сервер повертає повідомлення "Книга видалена успішно";
  else (Ні)
    :Сервер повертає повідомлення про помилку видалення;
  endif
else (Ні)
  :Сервер повертає повідомлення "Книга не знайдена";
endif

|Клієнт|
if (Відповідь успішна?) then (Так)
  :Клієнт відображає повідомлення "Книга видалена успішно";
else (Ні)
  :Клієнт відображає повідомлення про помилку або "Книга не знайдена";
endif
stop
@enduml
