@startuml
|Клієнт|
start
:Адміністратор обирає опцію "Переглянути книгу";
:Адміністратор вводить унікальний _id книги;
:Клієнт надсилає запит на сервер із _id книги;

|Сервер|
:Сервер отримує _id книги;
:Сервер перевіряє існування книги в базі;

if (Книга існує?) then (Так)
  :Сервер отримує дані книги (назва, автор, рік публікації, дата створення, дата оновлення);
  :Сервер повертає дані клієнту;
else (Ні)
  :Сервер повертає повідомлення "Книга не знайдена";
endif

|Клієнт|
if (Відповідь містить дані книги?) then (Так)
  :Клієнт відображає детальну інформацію про книгу;
else (Ні)
  :Клієнт відображає повідомлення "Книга не знайдена";
endif
stop
@enduml
