@startuml
|Клієнт|
start
:Адміністратор вводить дані для перевірки (назва, автор, рік публікації);
:Клієнт надсилає введені дані на сервер;

|Сервер|
:Сервер отримує дані;
:Сервер перевіряє поле "Рік публікації" (publishYear);
if (Рік публікації валідний?) then (Так)
  :Сервер перевіряє поле "Назва книги" (title);
  if (Поле "Назва книги" заповнене?) then (Так)
    :Сервер перевіряє поле "Автор" (author);
    if (Поле "Автор" заповнене?) then (Так)
      :Дані коректні;
      :Сервер повертає підтвердження успішної перевірки;
    else (Ні)
      :Сервер повертає повідомлення "Поле 'Автор' не заповнене";
    endif
  else (Ні)
    :Сервер повертає повідомлення "Поле 'Назва книги' не заповнене";
  endif
else (Ні)
  :Сервер повертає повідомлення "Некоректне значення 'Рік публікації'";
endif

|Клієнт|
if (Дані коректні?) then (Так)
  :Клієнт продовжує наступний процес;
else (Ні)
  :Клієнт відображає повідомлення про помилку;
endif
stop
@enduml
